sudo: required
services:
  - docker

before-install:
  - docker build -t shivendra30/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true shivendra30/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket-name: "elasticbeanstalk-us-east-2-875975483566"
  bucket-path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
