sudo: required
services:
  - docker

before-install:
  - docker build -t shivendra30/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true shivendra30/react-docker npm run test -- --coverage
